services:
  - type: web
    name: goal-tracker-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT main:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: goal-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /health

databases:
  - name: goal-tracker-db
    databaseName: goal_tracker
    user: goal_tracker
    plan: free
