services:
  - type: web
    name: goal-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fitness-app-main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: false
