services:
  # Backend API Service
  - type: web
    name: goal-tracker-api
    env: python
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: goal-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: https://goal-tracker-frontend.onrender.com

  # Frontend Service
  - type: web
    name: goal-tracker-frontend
    env: node
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://goal-tracker-api.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-store

# Database
databases:
  - name: ai_tracker_database
    databaseName: goal_tracker
    user: goal_tracker
    plan: free
